name: Summarize new issues

on:
 pull_request:
    types: [opened]

jobs:
     AddingnewAIfeature:
       - name: AI-based PR Reviewer & Summarizer with Chat Capabilities
         uses: coderabbitai/ai-pr-reviewer@1.16.2


   
